from decoder.ice.icemsg.segments import *

MsgTypeIndex = {
    'C': (MarketSnapshot,                     'MarketSnapshot'),
    'G': (Trade,                              'Trade'),
    'Y': (SpotTrade,                          'SpotTrade'),
    'H': (InvestigatedTrade,                  'InvestigatedTrade'),
    'I': (CancelledTrade,                     'CancelledTrade'),
    'J': (MarketStatistics,                   'MarketStatistics'),
    'K': (MarketStateChange,                  'MarketStateChange'),
    'L': (SystemText,                         'SystemText'),
    'M': (OpenInterest,                       'OpenInterest'),
    'N': (OpenPrice,                          'OpenPrice'),
    'c': (ClosePrice,                         'ClosePrice'), #v1.1.22
    'O': (SettlementPrice,                    'SettlementPrice'),
    'z': (MarkerIndexPrices,                  'MarkerIndexPrices'),
    'u': (EndOfDayMarketSummary,              'EndOfDayMarketSummary'),
    'f': (MarketEvent,                        'MarketEvent'),
    'g': (PreOpenPriceIndicator,              'PreOpenPriceIndicator'),
    'V': (IntervalPriceLimitNotification,     'IntervalPriceLimitNotification'),
    '9': (NewFuturesStrategyDefinition,       'NewFuturesStrategyDefinition'),
    'R': (NewExpiry,                          'NewExpiry'), #v1.1.22
    'b': (SpecialField,                       'SpecialField'), #v1.1.22
    '?': (UnknownTest,                        'UnknownTest'),
    'D': (SnapshotOrder,                      'SnapshotOrder'),
    'E': (AddModifyOrder,                     'AddModifyOrder'),
    'F': (DeleteOrder,                        'DeleteOrder'),
    'T': (MessageBundleMarker,                'MessageBundleMarker'),
    'm': (SnapshotPriceLevel,                 'SnapshotPriceLevel'),
    't': (AddPriceLevel,                      'AddPriceLevel'),
    's': (ChangePriceLevel,                   'ChangePriceLevel'),
    'r': (DeletePriceLevel,                   'DeletePriceLevel'),
    'U': (NewOptionsStrategyDefinition,       'NewOptionsStrategyDefinition'),
    'l': (NewOptionsMarketDefinition,         'NewOptionsMarketDefinition'),
    'k': (RFQ,                                'RFQ'),
    'v': (OptionOpenInterest,                 'OptionOpenInterest'),
    'w': (OptionSettlementPrice,              'OptionSettlementPrice'),
    'W': (OldStyleOptionsTradeAndMarketStats, 'OldStyleOptionsTradeAndMarketStats'),
    # TCP Messages
    '1': (LoginRequest,                       'LoginRequest'),
    'A': (LoginResponse,                      'LoginResponse'),
    '2': (ProductDefRequest,                  'ProductDefRequest'),
    'B': (ProductDefResponseFutures,          'ProductDefResponseFutures'),
    'i': (StripInfo,                          'StripInfo'),
    'p': (ProductDefResponseOptions,          'ProductDefResponseOptions'),
    'q': (StrategyDefResponseOptions,         'StrategyDefResponseOptions'),
    'd': (StrategyDefResponseFutures,         'StrategyDefResponseFutures'),
    '7': (HistoricalRequest,                  'HistoricalRequest'),
    '8': (HistoricalResponse,                 'HistoricalResponse'),
    '5': (DebugRequest,                       'DebugRequest'),
    'P': (DebugResponse,                      'DebugResponse'),
    'Q': (HeartBeat,                          'HeartBeat'),
    '6': (LogoutRequest,                      'LogoutRequest'),
    'S': (ErrorResponse,                      'ErrorResponse')
}
