from decoder.ice.ice.segments import *

MsgTypeIndex = {
    'Y': (MarketSnapshot                    ,'MarketSnapshot'                    ),
    'G': (Trade, 'Trade'),
    'Y': (SpotTrade                         ,'SpotTrade'                         ),
    'H': (InvestigatedTrade                 ,'InvestigatedTrade'                 ),
    'I': (CancelledTrade                    ,'CancelledTrade'                    ),  
    'J': (MarketStatistics                  ,'MarketStatistics'                  ),
    'K': (MarketStateChange                 ,'MarketStateChange'                 ),
    'L': (SystemText                        ,'SystemText'                        ),
    'M': (OpenInterest                      ,'OpenInterest'                      ),
    'N': (OpenPrice                         ,'OpenPrice'                         ),
    'O': (SettlementPrice                   ,'SettlementPrice'                   ),
    'z': (MarkerIndexPrices                 ,'MarkerIndexPrices'                 ),
    'u': (EndOfDayMarketSummary             ,'EndOfDayMarketSummary'             ),
    'f': (MarketEvent                       ,'MarketEvent'                       ),
    'g': (PreOpenPriceIndicator             ,'PreOpenPriceIndicator'             ),
    'i': (StripInfo                         ,'StripInfo'                         ),
    'V': (IntervalPriceLimitNotification    ,'IntervalPriceLimitNotification'    ),
    '9': (NewFuturesStrategyDefinition      ,'NewFuturesStrategyDefinition'      ),
    '?': (UnknownTest                       ,'UnknownTest'                       ),
    'D': (SnapshotOrder                     ,'SnapshotOrder'                     ),
    'E': (AddModifyOrder                    ,'AddModifyOrder'                    ),
    'F': (DeleteOrder                       ,'DeleteOrder'                       ),
    'T': (MessageBundleMarker               ,'MessageBundleMarker'               ),
    'm': (SnapshotPriceLevel                ,'SnapshotPriceLevel'                ),
    't': (AddPriceLevel                     ,'AddPriceLevel'                     ),
    's': (ChangePriceLevel                  ,'ChangePriceLevel'                  ),
    'r': (DeletePriceLevel                  ,'DeletePriceLevel'                  ),
    'U': (NewOptionsStrategyDefinition      ,'NewOptionsStrategyDefinition'      ),
    'l': (NewOptionsMarketDefinition        ,'NewOptionsMarketDefinition'        ),
    'k': (RFQ                               ,'RFQ'                               ),
    'v': (OptionOpenInterest                ,'OptionOpenInterest'                ),
    'w': (OptionSettlementPrice             ,'OptionSettlementPrice'             ),
    'W': (OldStyleOptionsTradeAndMarketStats,'OldStyleOptionsTradeAndMarketStats'),
}
